### ISSUE TITLE
Can't seem to build the HTML files

### ISSUE THREAD

**Issue by corsbj** [MicrosoftDocs/dynamics365smb-docs#105]
When I try to build the HTML files with openpublishing.build.ps1, it errors out trying to reach https://github.com/Microsoft/templates.docs.msft and https://github.com/Microsoft/templates.docs.msft.pdf, see below.
I've searched a bit and it seems those are private repos. How should I go about building the HTML files?

PS C:\Temp\Help2> .\.openpublishing.build.ps1
download build core script to local with source url: https://opbuildstorageprod.blob.core.windows.net/opps1container/.openpublishing.buildcore.ps1
run build core script with parameters:
[2019-01-29 13:46:19.301679Z]: Running build core ps1 with parameters:
[2019-01-29 13:46:19.312141Z]: Current PowerShell environment version: 5.1.17763.134
[2019-01-29 13:46:19.313138Z]: Default system value:
[2019-01-29 13:46:19.319121Z]:
Name                           Value
----                           -----
ReplayErrorWarningLogs         True
UserSpecifiedChangeListTsvF...
NeedBuildMdproj                True
MdprojTargets                  build
EnableSyncAggregation          False
NeedGenerateIntellisense       False
GitCloneRepositoryTimeOutIn... 600
UseTemplateWithCachedCommitId  False
UseDocfxV3                     False
LogOutputFolder                C:\Temp\Help2\log
EnableXrefmapResolver          True
UpdateNugetConfig              True
PreservedContentTypeMapping    {ManagedReference, RESTOperationGroup, Landing, JavaScriptReference...}
GitOtherOperationsTimeOutIn... 60
BuildType
PdfTemplateFolder
TocChangeTriggerFullBuild      False
UserSpecifiedDependentListF...
GitPullRepositoryTimeOutInS... 300
ResolveUserProfileByAccessT... True
MinimumCommonPackageVersion    1.63.0
AbandonGitUserProfileLocalC... True
DefaultWarningLogCodesString
EnableIncrementalPostProces... True
LogLevel                       Info
DefaultIntellisenseInfoLogC... DuplicateUids
PreservedFallbackCopyFileSe... toc.md,toc.yml
DefaultSubmoduleBranch         master
EnableCustomMetadataValidation False
ResolveUserProfile             False
PdfConvertParallelism          4
PreservedFallbackFolderRegex   (?i)_repo\.(.+-.+)
UpdateMdproj                   True
EnableMasterRedirectionFile    True
DefaultMaxRetryCount           3
EnableIncrementalBuild         True
EnableFileMapGenerator         True
EnableCustomValidation         True
NeedFetchSubmodule             True
ResolveUserProfileUsingGitHub  True
DefaultInfoLogCodesString
NonPublishedCopyFileSearchP...
DefaultIntellisenseErrorLog...
UpdateNugetExe                 False
StepProgressInfoFile
IsServerBuild                  False
SkipDereferenceForPR           False
DownloadNugetExeTimeOutInSe... 300
MinimumEntryPointPackageVer... 1.63.0
BuildToolParallelism           0
EnableBuildToolDebugModel      True
GlobalMetadataFile
PreservedTemplateFolders       {_themes, _themes.MSDN.Modern, _themes.MSDN.PartnerCenter, _themes.VS.Modern...}
AzureLocalizedRepositoryUrl... (?i)(https://(.*)?github.com/MicrosoftDocs/azure-docs-pr\.(.+\-.+)(\.git)?)|(https://(.*)?github.com/wacn/mc-docs-pr\.(.+\-.+)(\.git)?)
CopyFileFromFallbackFolders    True
DefaultEntryPoint              op
EnableFallbackPlugin           True
EnvironmentResourcesFile
CopyFileSearchPatternForGen... *.jpg,*.png,*.svg,*.jpeg,*.gif
EnableGitFeatures              True
FullDependentListFilePath
CacheFolder                    C:\Temp\Help2\.optemp\cache
IsDynamicRendering             False
DownloadNugetConfigTimeOutI... 30
ResourceContainerUrl           https://opbuildstorageprod.blob.core.windows.net/opps1container
DefaultIntellisenseWarningL...
EnablePdfHeaderFooter          False
DefaultErrorLogCodesString     InvalidInclude,InvalidCodeSnippet,InvalidInlineCodeSnippet
AllowUseDynamicRendering       False
NeedGeneratePdfExternalLink    True
ForceInitialize                False
NormalizeContentInBuildTool    False
NeedGeneratePdf                False
OutputFolder                   C:\Temp\Help2\_site
UpdatePackagesConfig           True
ContributionBranch
PreservedXrefServiceEndpoin... {NonProduction, Production}
[2019-01-29 13:46:19.389933Z]: Parse parameters
[2019-01-29 13:46:19.405890Z]: cleaning up C:\Temp\Help2\log\report.txt...
[13:46:19.417895Z]: There is no BuildConfigFile parameter, build with systemDefaultVariables
[2019-01-29 13:46:19.430823Z]: Create packages.config for entry-point package
[2019-01-29 13:46:19.454759Z]: Download Nuget tool and config
[2019-01-29 13:46:19.456754Z]: Running script within internal environment.
[13:46:19.480691Z]: Download file to C:\Temp\Help2\.optemp\Tools\Nuget\Nuget.Config from https://opbuildstorageprod.blob.core.windows.net/opps1container/Tools/Nuget/Nuget.Config with force: True
[13:46:19.501634Z]: Start to run command [Invoke-WebRequest] with args [
Name                           Value
----                           -----
TimeoutSec                     30
ErrorAction                    Stop
Uri                            https://opbuildstorageprod.blob.core.windows.net/opps1container/Tools/Nuget/Nuget.Config
OutFile                        C:\Temp\Help2\.optemp\Tools\Nuget\Nuget.Config

].
[13:46:19.506621Z]: Calling iteration 1
[13:46:19.685278Z]: Command ['Invoke-WebRequest'] succeeded at iteration 1.
[13:46:19.708218Z]: add 'latest' to versionsToCheck array
[13:46:19.712696Z]: Try checking version latest for package opbuild.scripts...
[13:46:19.715921Z]: isReleaseVersionPackage is True
[13:46:19.717915Z]: isPrereleaseVersionPackage is False
[13:46:19.719910Z]: start to call GetPackageLatestVersion
[13:46:19.730882Z]: Use prerelease package for opbuild.scripts : False
[13:46:25.658165Z]: packageVersion 1.69.0 is equal or larger than minAllowedVersion 1.63.0

id              : opbuild.scripts
version         : 1.69.0
targetFramework : net45

[2019-01-29 13:46:25.688093Z]: Restore entry-point package: opbuild.scripts
[2019-01-29 13:46:26.195437Z]: Allow use of dynamic rendering: False
[2019-01-29 13:46:26.230312Z]: Enable git features is: True
[2019-01-29 13:46:26.239313Z]: Call build entry point at C:\Temp\Help2\.optemp\packages\opbuild.scripts.1.69.0\tools\build.entrypoint.ps1
[2019-01-29 13:46:28.392554Z]: Parse build entry point from publish configuration: C:\Temp\Help2\.openpublishing.publish.config.json
[2019-01-29 13:46:28.439404Z]: Build entry point is op

id              : docfx
version         : 2.40.8
targetFramework : net45

id              : docfx.console
version         : 2.40.8
targetFramework : net45

id              : opbuild.filemapgenerator
version         : 1.69.0
targetFramework : net45

id              : opbuild.templates.op
version         : 1.69.0
targetFramework : net45

id              : opbuild.templates.intellisense
version         : 1.69.0
targetFramework : net45

id              : opbuild.schemavalidationconsole
version         : 1.69.0
targetFramework : net45

id              : opbuild.htmltopdftool
version         : 1.69.0
targetFramework : net45

id              : opbuild.gitcontributorinformationresolver
version         : 1.69.0
targetFramework : net45

id              : opbuild.redirectionresolver
version         : 1.69.0
targetFramework : net45

id              : opbuild.resolvedependencyconsole
version         : 1.69.0
targetFramework : net45

id              : opbuild.customizelogfilewithlogcodes
version         : 1.69.0
targetFramework : net45

id              : opbuild.initializecrrtool
version         : 1.69.0
targetFramework : net45

id              : opbuild.syncrepositoryfileconsole
version         : 1.69.0
targetFramework : net45

id              : opbuild.xrefmapresolver
version         : 1.69.0
targetFramework : net45

id              : opbuild.manifestprocessor
version         : 1.69.0
targetFramework : net45

id              : opbuild.filemappreprocessor
version         : 1.69.0
targetFramework : net45

[2019-01-29 13:46:28.580020Z]: Restore build script dependent packages
[2019-01-29 13:46:30.345647Z]: C:\Temp\Help2\.optemp\packages\opbuild.initializecrrtool.1.69.0\tools\Microsoft.OpenPublishing.Build.Applications.InitializeCRRTool.exe --repository-root C:\Temp\Help2 --dependent-repositories [
    {
        \"path_to_root\":  \"_themes\",
        \"url\":  \"https://github.com/Microsoft/templates.docs.msft\",
        \"branch\":  \"master\",
        \"branch_mapping\":  {

                           }
    },
    {
        \"path_to_root\":  \"_themes.pdf\",
        \"url\":  \"https://github.com/Microsoft/templates.docs.msft.pdf\",
        \"branch\":  \"master\",
        \"branch_mapping\":  {

                           }
    }
] --preserved-template-folders _themes,_themes.MSDN.Modern,_themes.MSDN.PartnerCenter,_themes.VS.Modern,_themes.VS.UHF,_themes.TechNet.Modern,_themes.OPS,_themes.pdf --log C:\Temp\Help2\log\report.txt --output-file-path C:\Temp\Help2\.optemp\CRR\crrinformations.json
Verbose [29-01-2019 13:46:31][OPS.Microsoft.OpenPublishing.Build.Applications.InitializeCRRTool.exe]: Parent working branch is master
Verbose [29-01-2019 13:46:31][OPS.Microsoft.OpenPublishing.Build.Applications.InitializeCRRTool.exe]: Start to initialize dependent repository _themes.
Verbose [29-01-2019 13:46:31][OPS.Microsoft.OpenPublishing.Build.Applications.InitializeCRRTool.exe]: Start to initialize dependent repository _themes.pdf.
Verbose [29-01-2019 13:46:31][OPS.Microsoft.OpenPublishing.Build.Applications.InitializeCRRTool.exe]: Add '_themes' to cloned path
Verbose [29-01-2019 13:46:31][OPS.Microsoft.OpenPublishing.Build.Applications.InitializeCRRTool.exe]: Add '_themes.pdf' to cloned path
Verbose [29-01-2019 13:46:31][OPS.Microsoft.OpenPublishing.Build.Applications.InitializeCRRTool.exe]: Dependent repository https://github.com/Microsoft/templates.docs.msft.pdf is using branch: master
Verbose [29-01-2019 13:46:31][OPS.Microsoft.OpenPublishing.Build.Applications.InitializeCRRTool.exe]: Dependent repository https://github.com/Microsoft/templates.docs.msft is using branch: master
Verbose [29-01-2019 13:46:31][OPS.Microsoft.OpenPublishing.Build.Applications.InitializeCRRTool.exe]: Start to clone repository https://github.com/Microsoft/templates.docs.msft.pdf to C:\Temp\Help2\_themes.pdf...
[2019-01-29T13:46:31]: Error occurred when restoring dependency repo from URL 'https://github.com/Microsoft/templates.docs.msft' branch 'master' into folder '_themes': Microsoft.OpenPublishing.Build.DataAccessor.Git.GitDataAccessException: ExternalGitAccessor: data access error, argument: rev-parse --abbrev-ref HEAD, workingDirectory: C:\Temp\Help2\_themes, error code: 128, details: fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
.
   at Microsoft.OpenPublishing.Build.DataAccessor.Git.ExternalGitAccessor.ThrowGitDataAccessException(Int32 returnValue, String errorMessage, String workingDirectory, String argument, DataAccessErrorType dataAccessErrorType, Uri repositoryUrl, String branchName)
   at Microsoft.OpenPublishing.Build.DataAccessor.Git.ExternalGitAccessor.RunGitExeAndProcessOutputStream(String argument, String workingDirectory, Uri repositoryUrl, String branchName, Action`1 outPutStreamAction, Boolean silentException, Int32 timeout, Boolean retryOnTimeout)
   at Microsoft.OpenPublishing.Build.DataAccessor.Git.ExternalGitAccessor.RunGitExeAndGetSingleLineOutput(String argument, String workingDirectory, Uri repositoryUrl, String branchName, Boolean silentException, Int32 timeout, Boolean retryOnTimeout)
   at Microsoft.OpenPublishing.Build.DataAccessor.Git.ExternalGitAccessor.get_HeadBranchName()
   at Microsoft.OpenPublishing.Build.Applications.InitializeCRRTool.Program.InitializeDependentRepository(String dependentRepoPath, String cloneAccessToken, Boolean isCopiedFromCachedRepo, Boolean isPreservedTemplateFolders, Options options, DependentRepository dependentRepository)
   at Microsoft.OpenPublishing.Build.Applications.InitializeCRRTool.Program.InitializeCRRCore(String dependentRepoPath, String cloneAccessToken, Boolean isPreservedTemplateFolders, Boolean isCopiedFromCachedRepo, String branch, Options options, DependentRepository dependentRepository, List`1 lastDependencyStatus)
   at Microsoft.OpenPublishing.Build.Applications.InitializeCRRTool.Program.InitializeCRR(DependentRepository dependentRepo, String workingDirectory, String workingBranchName, Options options, List`1 cachedRepositories, List`1 lastDependencyStatus)
   at Microsoft.OpenPublishing.Build.Applications.InitializeCRRTool.Program.<>c__DisplayClass3_1.<RunAsync>b__0(DependentRepository dependentRepo)
Error [29-01-2019 13:46:31][OPS.Microsoft.OpenPublishing.Build.Applications.InitializeCRRTool.exe]: Error occurred when restoring dependency repo from URL 'https://github.com/Microsoft/templates.docs.msft' branch 'master' into folder '_themes': ExternalGitAccessor: data access error, argument: rev-parse --abbrev-ref HEAD, workingDirectory: C:\Temp\Help2\_themes, error code: 128, details: fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
.
[2019-01-29T13:46:35]: Error occurred when restoring dependency repo from URL 'https://github.com/Microsoft/templates.docs.msft.pdf' branch 'master' into folder '_themes.pdf': Microsoft.OpenPublishing.Build.DataAccessor.Interface.GitAuthorizationException: Git data access to 'https://github.com/Microsoft/templates.docs.msft.pdf' is not authorized.
   at Microsoft.OpenPublishing.Build.DataAccessor.Git.ExternalGitAccessor.ThrowGitDataAccessException(Int32 returnValue, String errorMessage, String workingDirectory, String argument, DataAccessErrorType dataAccessErrorType, Uri repositoryUrl, String branchName)
   at Microsoft.OpenPublishing.Build.DataAccessor.Git.ExternalGitAccessor.RunGitExeAndProcessOutputStream(String argument, String workingDirectory, Uri repositoryUrl, String branchName, Action`1 outPutStreamAction, Boolean silentException, Int32 timeout, Boolean retryOnTimeout)
   at Microsoft.OpenPublishing.Build.DataAccessor.Git.ExternalGitAccessor.RunGitExeAndGetSingleLineOutput(String argument, String workingDirectory, Uri repositoryUrl, String branchName, Boolean silentException, Int32 timeout, Boolean retryOnTimeout)
   at Microsoft.OpenPublishing.Build.DataAccessor.Git.ExternalGitAccessor.<>c__DisplayClass61_0.<CloneRepository>b__0()
   at Microsoft.OpenPublishing.Build.Common.RetryHelper.Retry(Action action, Func`2[] errorHandlers, TimeSpan[] retryIntervals, String methodName, String filePath, Int32 lineNumber)
   at Microsoft.OpenPublishing.Build.DataAccessor.Git.ExternalGitAccessor.CloneRepository(Uri url, String workingDirectory, Int32 timeoutInMilliseconds, String userName, String accessToken)
   at Microsoft.OpenPublishing.Build.Applications.InitializeCRRTool.Program.CloneRepository(String url, String workingDirectory, String cloneAccessToken)
   at Microsoft.OpenPublishing.Build.Applications.InitializeCRRTool.Program.InitializeDependentRepository(String dependentRepoPath, String cloneAccessToken, Boolean isCopiedFromCachedRepo, Boolean isPreservedTemplateFolders, Options options, DependentRepository dependentRepository)
   at Microsoft.OpenPublishing.Build.Applications.InitializeCRRTool.Program.InitializeCRRCore(String dependentRepoPath, String cloneAccessToken, Boolean isPreservedTemplateFolders, Boolean isCopiedFromCachedRepo, String branch, Options options, DependentRepository dependentRepository, List`1 lastDependencyStatus)
   at Microsoft.OpenPublishing.Build.Applications.InitializeCRRTool.Program.InitializeCRR(DependentRepository dependentRepo, String workingDirectory, String workingBranchName, Options options, List`1 cachedRepositories, List`1 lastDependencyStatus)
   at Microsoft.OpenPublishing.Build.Applications.InitializeCRRTool.Program.<>c__DisplayClass3_1.<RunAsync>b__0(DependentRepository dependentRepo)
Error [29-01-2019 13:46:35][OPS.Microsoft.OpenPublishing.Build.Applications.InitializeCRRTool.exe]: Error occurred when restoring dependency repo from URL 'https://github.com/Microsoft/templates.docs.msft.pdf' branch 'master' into folder '_themes.pdf': You have no access permission to repository 'https://github.com/Microsoft/templates.docs.msft.pdf'
Initialize dependencies failed

**Comment by edupont04** [comment]
Hi corsbj,

It sounds like you are running DocFx from the root of your clone of the repo. You should change the path to run in the business-central folder. That way, the tool won't try to process the files that are there for the purposes of the Docs.microsoft.com site.
You can see an example of that described here: 
https://github.com/MicrosoftDocs/nav-content#building-the-html-files-from-the-markdown-files

**Comment by corsbj** [comment]
I wasn't running DocFx at all. I couldn't find that in any of the documentation for dynamics365smb-docs. 
All I could find was the powershell script, which didn't work.

The link you just provided help me get it done though. 
Can I suggest putting that somewhere in the readme?

**Comment by edupont04** [comment]
Here you go:
https://github.com/MicrosoftDocs/dynamics365smb-docs/#building-html-files
